railwaystation/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :wagons
    resources :tickets
    resources :routes
    resource :search, only: [:new, :show, :edit, :create]
  end

  get 'welcome/index'

  root to: 'searches#show'

end

railwaystation/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railwaystation - Администатор</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice" class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= link_to "Выйти", destroy_user_session_path, method: :delete %>
  <p>Аккаунт: <%= current_user.email %></p>
<% else %>
  <%= link_to "Войти", new_user_session_path %>
<% end %>


<%= yield %>

<footer class="page-footer">
  <center><span>© 2015 Максим Солопин. Учебный проект в онлайн-школе Thinknetica</span></center>
</footer>

</body>
</html>

railwaystation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railwaystation" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">RailwayStations</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
                <% if current_user.admin? %>
                  <li><%= link_to "Список станций", admin_railway_stations_path %></li>
                  <li><%= link_to "Список маршрутов", admin_routes_path %></li>
                  <li><%= link_to "Поезда", admin_trains_path %></li>
                  <li><%= link_to "Вагоны", admin_wagons_path %></li>
                  <li><%= link_to 'Поиск', admin_search_path %></li>
                  <li><%= link_to "Билеты", admin_tickets_path %></li>
                <% else %>
                  <li><%= link_to 'Билеты', tickets_path %></li>
                  <li><%= link_to 'Поиск', search_path %></li>
                <% end %>
            <% else %>
                <li><%= link_to "Войти", new_user_session_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>


    <%= bootstrap_flash %>

    <%= yield %>

    <footer class="page-footer">
      <center><span>© 2015 Максим Солопин. Учебный проект в онлайн-школе Thinknetica</span></center>
    </footer>

  </body>
</html>