railwaystation/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :wagons
    resources :tickets
    resources :routes
    resource :search, only: [:new, :show, :edit, :create]
  end

  get 'welcome/index'

  root to: 'searches#show'

end

railwaystation/app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
 validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :ordered, -> { select('railway_stations.*, railway_stations_routes.position').joins(:railway_stations_routes).order("railway_stations_routes.position").uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrival_time(route, arrival_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time) if station_route
  end

  def arrival_time_in(route)
    station_route(route).try(:arrival_time)
  end

  def update_departure_time(route, departure_time)
    station_route = station_route(route)
    station_route.update(departure_time: departure_time) if station_route
  end

  def departure_time_in(route)
    station_route(route).try(:departure_time)
  end



  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

railwaystation/app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position, :update_arrival_time, :update_departure_time]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to [:admin, railway_stations_url], notice: 'Railway station was successfully destroyed.'
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to [:admin, @route]
  end

  def update_arrival_time
    @route = Route.find(params[:route_id])
    @railway_station.update_arrival_time(@route, params[:arrival_time])
    redirect_to [:admin, @route]
  end

  def update_departure_time
    @route = Route.find(params[:route_id])
    @railway_station.update_departure_time(@route, params[:departure_time])
    redirect_to [:admin, @route]
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

railwaystation/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

railwaystation/app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, @railway_station] do |f| %>
  <%= render 'common/errors', resource: @railway_station %>

  <div class="row">
    <div class="col-lg-6">
      <%= f.label :title %>
      <div class="input-group">
        <%= f.text_field :title, class: 'form-control' %>
        <span class="input-group-btn">
          <%= f.submit t('.submit', action: @railway_station.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-default' %>
        </span>
      </div>
    </div>
  </div>

<% end %>

railwaystation/app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to t('common.show'), [:admin, railway_station], class: 'btn btn-link' %></td>
  <td><%= link_to t('common.edit'), edit_admin_railway_station_path(railway_station), class: 'btn btn-link' %></td>
  <td><%= link_to t('common.delete'), [:admin, railway_station] , method: :delete, data: { confirm: t('common.confirm') }, class: 'btn btn-link' %></td>
</tr>

railwaystation/app/views/admin/railway_stations/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= t('.title') %></h1>
  </div>

  <%= render 'form' %>
</div>

<nav>
  <ul class="pager">
    <%= link_to t('common.back'), admin_railway_stations_path %>
  </ul>
</nav>

railwaystation/app/views/admin/railway_stations/index.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= t('.title') %></h1>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('.th-title') %></th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @railway_stations %>
    </tbody>

  </table>
</div>

<nav>
  <ul class="pager">
    <li><%= link_to t('.new'), new_admin_railway_station_path %></li>
    <li><%= link_to t('common.root'), root_path %></li>
  </ul>
</nav>

railwaystation/app/views/admin/railway_stations/new.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= t('.title') %></h1>
  </div>

  <%= render 'form' %>
</div>

<nav>
  <ul class="pager">
    <li><%= link_to t('common.back'), admin_railway_stations_path %></li>
  </ul>
</nav>

railwaystation/app/views/admin/railway_stations/show.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= t('.title') %></h1>
  </div>

  <p>
    <strong><%= t('.p-title') %></strong>
    <%= @railway_station.title %>
  </p>

  <% if @railway_station.routes.empty? %>
      <p><%= t('.routes-empty') %></p>
  <% else %>
      <p><%= t('.routes') %></p>
      <ul class="list-group">
        <% @railway_station.routes.each do |route| %>
          <li class="list-group-item"><%= route.name %></li>
        <% end %>
      </ul>
  <% end %>
</div>

<nav>
  <ul class="pager">
    <li><%= link_to t('common.edit'), edit_admin_railway_station_path(@railway_station) %></li>
    <li><%= link_to t('common.back'), admin_railway_stations_path %></li>
  </ul>
</nav>