railwaystation/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :wagons
    resources :tickets
    resources :routes
    resource :search, only: [:new, :show, :edit, :create]
  end

  get 'welcome/index'

  root to: 'searches#show'

end

railwaystation/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true

  has_many :tickets

  scope :not_admin_users, -> { where(admin: false) }

end

railwaystation/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

railwaystation/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= render 'common/errors', resource: @user %>

  <div class="field">
    <%= f.label :name, "ФИО:" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @user.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

railwaystation/app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= link_to 'Показать', user %></td>
  <td><%= link_to 'Редактировать', edit_user_path(user) %></td>
  <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

railwaystation/app/views/users/edit.html.erb
<h1>Изменить пользователя</h1>

<%= render 'form' %>

<%= link_to 'Пользователь', @user %> |
<%= link_to 'Назад', users_path %>

railwaystation/app/views/users/index.html.erb
<h1>Список пользователей</h1>

<table>
  <thead>
    <tr>
      <th>ФИО</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить пользователя', new_user_path %>
<%= link_to 'Главное меню', root_path %>

railwaystation/app/views/users/new.html.erb
<h1>Добавить пользователя</h1>

<%= render 'form' %>

<%= link_to 'Назад', users_path %>

railwaystation/app/views/users/show.html.erb
<p>
  Имя:
  <strong><%= @user.name %></strong>
</p>
<%= link_to 'Список билетов пользователя:', user_tickets_path(@user) %>
<br><br>
<table >
  <thead>
    <tr>
      <td>№</td>
      <td>Номер билета</td>
      <td>Номер поезда</td>
      <td>Отправление</td>
      <td>Прибытие</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% number = 0 %>
    <% @user.tickets.each do |ticket| %>
      <tr>
        <td><%= number %>.</td>
        <td><%= ticket.number %></td>
        <td><%= ticket.train %></td>
        <td><%= ticket.departure_statition.title %></td>
        <td><%= ticket.arrival_statition.title %></td>
        <td><%= link_to 'Билет', user_ticket_path(@user, ticket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Редактировать', edit_user_path(@user) %> |
<%= link_to 'Назад к пользователям', users_path %>