railwaystation/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :wagons
    resources :tickets
    resources :routes
    resource :search, only: [:new, :show, :edit, :create]
  end

  get 'welcome/index'

  root to: 'searches#show'

end

railwaystation/app/models/train.rb
class Train < ActiveRecord::Base
    TRAIN_SORT_TYPES = ["DESC", "ASC"]

    validates :number, uniqueness: true

    belongs_to :route
    has_many :tickets
    has_many :wagons

    #scope :ordered, -> (train, direction) { where(train: train).order("number #{direction}") }


    def compartment_wagon_count
        self.wagons.select{|wagon| wagon.wagon_type == "Купейный" }.size
    end

    def econom_wagon_count
        self.wagons.select{|wagon| wagon.wagon_type == "Плацкартный" }.size
    end

    def count_seats
        count_compartments_bottom_seats = 0
        count_compartments_top_seats = 0
        count_reserved_bottom_seats = 0
        count_reserved_top_seats = 0

        self.wagons.each do |wagon|
            if wagon.wagon_type == "Купейный"
                count_compartments_bottom_seats += wagon.bottom_seats_count
                count_compartments_top_seats += wagon.top_seats_count
            elsif wagon.wagon_type == "Плацкартный"
                count_reserved_bottom_seats += wagon.bottom_seats_count
                count_reserved_top_seats += wagon.top_seats_count
            end
        end

        return count_compartments_bottom_seats, count_compartments_top_seats, count_reserved_bottom_seats, count_reserved_top_seats
    end

    def self.find_trains(routes)
        Train.joins(:route).where("route_id in (?)", routes)
    end

    def route_arrival_time
        self.route.railway_stations.ordered.first.arrival_time_in(self.route)
    end

    def route_departure_time
        self.route.railway_stations.ordered.first.departure_time_in(self.route)
    end

end

railwaystation/app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
   before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to [:admin, @train]
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id, :sorting_order_flag)
  end
end

railwaystation/app/helpers/trains_helper.rb
module TrainsHelper
end

railwaystation/app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |f| %>
    <%= render 'common/errors', resource: @train %>

    <div class="field">
      <%= f.label :number %><br>
      <%= f.text_field :number %>
    </div>

    <div class="field">
      <%= f.label :route, "Текущий маршрут" %>
      <%= f.collection_select :route_id, Route.all, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :sorting_order_flag %><br>
      <%= f.select(:sorting_order_flag, Train::TRAIN_SORT_TYPES) %>
    </div>

    <div class="actions">
      <%= f.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
    </div>

<% end %>

railwaystation/app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', [:admin, train] %></td>
  <td><%= link_to 'Редактировать', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Удалить', [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

railwaystation/app/views/admin/trains/edit.html.erb
<h1>Изменение поезда</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_trains_path %>

railwaystation/app/views/admin/trains/index.html.erb
<h1>Список поездов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_admin_train_path %>
<%= link_to 'Главное меню', root_path %>

railwaystation/app/views/admin/trains/new.html.erb
<h1>Добавить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_trains_path %>

railwaystation/app/views/admin/trains/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Маршрут не назначен
  <% end %>
</p>

<p>
    <strong>Кол-во вагонов:</strong><br>

    <strong>Купейных:</strong>
    <%= @train.compartment_wagon_count %><br>

    <% count_compartments_bottom_seats, count_compartments_top_seats, count_reserved_bottom_seats, count_reserved_top_seats = @train.count_seats %>

    <strong>Кол-во верхних мест:</strong>
    <%= count_compartments_top_seats %> <br>
    <strong>Кол-во нижних мест:</strong>
    <%= count_compartments_bottom_seats %> <br>

    <strong>Плацкартных:</strong>
    <%= @train.econom_wagon_count %><br>

    <strong>Кол-во верхних мест:</strong>
    <%= count_reserved_top_seats %> <br>
    <strong>Кол-во нижних мест:</strong>
    <%= count_reserved_bottom_seats %> <br>
</p>

<p>
  <strong>Вагоны</strong>
  <ul>
    <% @train.wagons.ordered(@train.sorting_order_flag).each do |wagon| %>
        <li><%= link_to "Вагон №#{wagon.number}", wagon %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Флаг сортировки:</strong>
  <%= @train.sorting_order_flag %>
</p>

<p>
  <%= link_to "Добавить вагон", new_admin_train_wagon_path(@train) %>
</p>

<%= link_to 'Редактировать', edit_admin_train_path(@train) %> |
<%= link_to 'Назад', admin_trains_path %>